version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    ports: 
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html:delegated

  mysql:
    image: mysql:5.7
    platform: linux/x86_64 # Please remove if you do not use macOS M1
    container_name: pecc3web
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql      
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes: 
      - ./wordpress:/var/www/html:delegated
